### ISSUE TITLE
NOAA Enterprise Data Mgmt (EDMW) - May 14 presentation (May 13-17 conf)

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/workshop-planning#61]
**Whole Workshop Schedule:** May 13 - 17, 2024
**Venue:** Virtual Only
**Goal:** share data success stories, innovations in our work, and our vision of achieving equitable data outcomes for NOAA staff and partners.
**Workshop Theme:** Bridging the Gap: Ensuring Seamless Data Flow from Acquisition to Access
**Cloud Native Session:** 90 minutes, 4-6 speakers, 5-10 minute presentations followed by group discussion. 
**Proposed Presentation:** NASA Openscapes: building and expanding capacity for cloud-native access of NASA data
**May 14 11:45am-1:15pm ET, Session II - invited talk**

**More information:**
The NOAA Enterprise Data Management Workshop (EDMW) is an annual workshop organized by NOAA staff and affiliates. The purpose of the workshop is to build on past work in enterprise data management at NOAA by highlighting progress, identifying issues, fostering discussions, and determining where new technologies can be applied.

**Comment by BriannaLind** [comment]
@jules32 would you be able to cover this?  It is strongly possible I will be at an in-person workshop

**Comment by jules32** [comment]
Hi @BriannaLind , yes happy to help here. Would you cc me to let them know along with any further details you have about the session at this point? Thanks!

**Comment by BriannaLind** [comment]
Need to add send abstract to Aimee B. 

Fill out [this form](([https://docs.google.com/forms/d/e/1FAIpQLSfJ4ct8jWrKHm6q4KwzMh6T0udwzZDsZyPsVO2jsXzmaLbSTw/viewform](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSfJ4ct8jWrKHm6q4KwzMh6T0udwzZDsZyPsVO2jsXzmaLbSTw%2Fviewform&data=05%7C02%7Cblind%40contractor.usgs.gov%7Cd9239057350e461eecff08dc3e0b9273%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638453466627584717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=GkgRZ%2FiHoaMAdb%2BphWfdTB1XyUB8gDa%2FY6rgjGfYzYc%3D&reserved=0))) to register for the workshop

**Comment by BriannaLind** [comment]
[heart]         Lind, Brianna (Contractor) reacted to your message:
________________________________
From: Julia Stewart Lowndes ***@***.***>
Sent: Tuesday, March 12, 2024 7:16:02 PM
To: NASA-Openscapes/workshop-planning ***@***.***>
Cc: Lind, Brianna (Contractor) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-Openscapes/workshop-planning] NOAA Enterprise Data Mgmt (EDMW) - May 13-17 (Issue #61)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Abstract:

NASA Openscapes<https://nasa-openscapes.github.io/> is a community where staff with similar roles supporting users across 12 NASA Earth Science Data Centers (DAACs<https://www.earthdata.nasa.gov/eosdis/daacs>) have been able to learn, develop common tutorials, and teach together to support users migrating workflows to the Cloud. NASA Openscapes Mentors co-create and maintain an open Earthdata Cloud Cookbook<https://nasa-openscapes.github.io/earthdata-cloud-cookbook/> of common reusable open source tutorials that they have co-developed for specific audiences and tested and refined through frequent workshops, hackathons, and Openscapes Champions Cohorts. They also created the earthaccess Python library<https://earthaccess.readthedocs.io/> which made users' first experience with NASA Earthdata Cloud be two lines of Python code rather than 30 lines of bash code (that also required clicking and managing hidden files for authentication). The work these Mentors do together as a small community has enormous cascading effects, particularly as they visibly practice open science daily via contributions to open source code and documentation. Further, they are connected to other open communities to enable further innovation: like when a conversation at the Ecological Society of America conference led to building the earthdatalogin R library<https://boettiger-lab.github.io/earthdatalogin/index.html> to support researchers R as well as Python and create portable docker containers cloud users. We will share stories and how we work, and how approaches fit and can be leveraged by the NOAA Enterprise Data Management community.

**Comment by jules32** [comment]
Brainstorming talk outline. 10 mins max (10 max slides). For this audience, want to share quick context then also current activities and learning/work in progress. 

Slide : 

1. Openscapes open source community: learning, doing, building together across academia and government. Zoom faces montage behind.
2. Landscape illustration. Kinder science for future us. Teams, navigating
3. NASA openscapes. Community of professional staff and similar roles across 12 data centers at nasa Earth data. Learning community collaborate shared practices. Teaching oriented.
4. shell graphic - Learn together first, teach and document and onboard, teach scientists, connect with the broader open source community and give back. Champions program is one format where we get to know user is very deeply - Led to Earth access and Matlab and are in the hub. 
5. A lot of different parts of this four main goals/activities right now.
6. What's made this possible is really a focus on tech and the social infrastructure over and over throughout. Becoming teachers coaching skills, listening mentoring live coding carpentries. Tech infrastructure to i2c open source communities, etc.
7. Challenges and things we're working on now. Storage in the hub workshop architecture
8. .
9. . Closing thoughts
10. Thank you

**Comment by jules32** [comment]
Copying from https://github.com/NASA-Openscapes/workshop-planning/issues/32#issuecomment-2064453095

Hello Session presenters, Chairs, and Workshop support team,

The EDMW is less than one month away, and we’re grateful for your help in making it happen!

As we are conducting this workshop virtually, we will be recording all sessions so that NOAA team members and invited guests can experience more of the Workshop.

To appear on camera, you must fill out the attached Likeness and Profile Release form. At the bottom of the form is also a Privacy Act Statement. If you choose not to provide consent via the form, we’ll ask you to turn your camera off; however, any presentation you make and your voice can still be recorded.

NOTE TO PRIMARY AUTHORS: Please forward this form to your co-authors if they wish to appear onscreen or their photo likeness will be used during your presentation. Co-authors not planning to appear on screen during your presentation do not need to submit the form.

Please e-sign and upload the form to [this folder](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F1xpczMybvQbHcDpeY_xaQYkwpLHSb6kiB%3Fusp%3Ddrive_link&data=05%7C02%7Cblind%40contractor.usgs.gov%7Cd2109850c8a44fa8d9ba08dc5fba08c2%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638490499819038072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Gxy2yHp9OPfqW8LuxGozlrwM6XVcf77HVw5RXx70frA%3D&reserved=0) by COB May 3, 2024. If you do not have access to Adobe Reader, Acrobat, or other PDF tools, please print out the form, fill it out, sign it, scan or take a photo, and upload it.

If you have any questions, please email [edmw.planning.team@noaa.gov](mailto:edmw.planning.team@noaa.gov).

**Comment by jules32** [comment]
@itcarroll will be co-presenting! We are huddling about the slides on May 10.

**Comment by jules32** [comment]
Ian and I met and have a good plan! A little more slide polishing but I'll present the first half and Ian the second. Slides: 
https://docs.google.com/presentation/d/1gkdlVU-5WEb3-nB5Wjprw61BE4CVDjHbgTwoyd59ckA/edit#slide=id.g262cd94a96b_0_0

**Comment by jules32** [comment]
Ian from the NASA Ocean Biology data center (OB.DAAC) and I presented this morning in 2 back-to-back talks for the NASA CDDIS Data Center user working group and the NOAA Enterprise Data Management Workshop (15 mins apart!): How the NASA Openscapes community supports Earthdata users migrating workflows to the Cloud ([slides](https://docs.google.com/presentation/d/1gkdlVU-5WEb3-nB5Wjprw61BE4CVDjHbgTwoyd59ckA/edit#slide=id.g262cd94a96b_0_0), [web](https://nasa-openscapes.github.io/about.html#slides) so you can find slides again). We were able to present to both audiences using the same slide deck and adapt our spoken language to connect with the specific communities, and we got good questions/followup in each! Thanks Ian, it was awesome to co-present and a good practice for time-limited, adapt on the fly open science!
