### ISSUE TITLE
EMIT Methane Webinar

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/workshop-planning#9]
## EMIT Methane Webinar

**Comment by BriannaLind** [comment]
- [ ] add list
- [ ] this is a list
- [ ] this is still a list

**Comment by BriannaLind** [comment]
- Do what can with methane plumes ..... look at time sequence, etc. caveats
- they are using a STAC API that they deployed.....? how do we want to approach that? Do it outside of GHG center for now
- should generate STAC catalog on ingest (if can stand up API easy to deliver)
- 
- 
Will learn more on March 14th Want to bring in additional layers

**Comment by BriannaLind** [comment]
---> turn original components of notebooks into webbook prior to GHG event promotion point people resource to the front end.
---> move towards webbook as can

Check ambitiousness of webbook for GHG ........ do a time series analysis; Rob's favorite plume (a landfill in Jordan (country)). How important is it to think about 'sensitivity' of background image. in Turkmenistan?.... if they get rid of leaks, its great!  Want a tool to know when the leak  DC/Baltimore?

**Comment by jules32** [comment]
From @stefaniebutland: 

Good morning @jules32 , This DM w you and @BriannaLind is to update us on EMIT workshop 2i2c status.

- Bri and I invited >150 folks to workshop team: https://github.com/orgs/nasa-openscapes-workshops/teams/emit-methane-plume-2024-03-14
- She's sending headsup emails now
- Bri had / has to do some cleaning of her workshop responses sheet; the github username column had lots of bad data. There are ~50 usernames we'll need to add prior to /at start of workshop.
  - :question: Do you need Bri to add the workshop form data to our main Openscapes_JupyterHubAccess (Responses) sheet asap and before the workshop? Or is after workshop ok?
- Aaron and Mahsa are workshop helpers. I've invited them to [AdminTeam](https://github.com/orgs/nasa-openscapes-workshops/teams/adminteam) for during-workshop Teams help
  - :question: Wondering how/what setting I need to do to ensure they have Teams "Maintainer" permission. Asking because Catalina is on AdminTeam but does not show when I view role: Maintainer

![Image](https://github.com/NASA-Openscapes/workshop-planning/assets/5891909/c43b682f-50f8-4fb5-8fdf-2c561b97db54)
- I'll add more batches to workshop Team as Bri requests

**Comment by jules32** [comment]
Hi @stefaniebutland , in response to your questions (❓ )

- please add the workshop names asap as they are cleaned up; otherwise too easy for this information to get lost
- "Maintainer" - This is a second step that we'll have to do. From the [Admin Team page](https://github.com/orgs/nasa-openscapes-workshops/teams/adminteam?query=), you click on Catalina's name, then change the Role to Owner. Then she will show up as a Maintainer. 

![Image](https://github.com/NASA-Openscapes/workshop-planning/assets/5891909/d1ca67a8-4a82-476a-a564-98a232888444)

@stefaniebutland , will you please test this process with Aaron and Mahsa?

**Comment by stefaniebutland** [comment]
Thanks Bri for adding folks to our main Openscapes_JupyterHubAccess (Responses) sheet!

**Comment by BriannaLind** [comment]
Improvement ideas:

- Consider having meeting link available before setting up signup form...... this way can reach out for a reminder; but not strictly necessary
- Set up form to automatically send and email to participants providing link?
- Set up automatic email reminder before event?

**Comment by amfriesz** [comment]
Parking some links I had gathered for the webinar here.

## Relevant Links

**GHG Center** - https://earth.gov/ghgcenter

**Join Slack** - https://forms.gle/XefLVG6e6A7ezwpY9

### Notes

- https://docs.google.com/document/d/1iZRJMps48FEQ0ebepfVLbqqCf1ttt2w1VfEp-1cRmKc/edit#heading=h.6bwtopfrdnn1

### JupyterHub

User NBGitPuller link to launch a JupyterLab instance and Clone the repo
- NBGitPuller - https://tinyurl.com/mvxbtzmp

If the NBGitPuller link pathway fails for any reason, close and try again. If it fails again manually launch the JupyterLab instance and clone the repo into your work environment.
- JupyterHub Link - https://openscapes.2i2c.cloud/hub/home
    > git clone https://github.com/nasa/EMIT-Data-Resources
    > cd EMIT-Data-Resources

### Repositories

- EMIT Data Resources - https://github.com/nasa/EMIT-Data-Resources

### Product Info

- EMIT L2B Methane Enhancement Data - https://lpdaac.usgs.gov/products/emitl2bch4enhv001/
- EMIT L2B Estimated Methane Plume Complexes - https://lpdaac.usgs.gov/products/emitl2bch4plmv001/

### EMIT in AppEEARS

- Announcement - https://lpdaac.usgs.gov/news/release-of-arreears-version-347-emit-radiance-and-reflectance-data-products-now-available/
- AppEEARS - https://appeears.earthdatacloud.nasa.gov/

### GitHub Logistics

**Add to GitHub Team**

- https://github.com/orgs/nasa-openscapes-workshops/teams/emit-methane-plume-2024-03-14

Have added members go to the following link to `View Invitation` and `Accept Invite`
- https://github.com/orgs/nasa-openscapes-workshops/teams

### Past Videos

- https://earth.jpl.nasa.gov/emit/events/4/emit-data-tutorial-series/
- https://www.youtube.com/playlist?list=PLO2yB4LGNlWrC5NdxeHMxyAxdwQhSypXe
